import type { Company, Ledger, User, Voucher, Note, Item } from './types';

export const mockUser: User = {
  userId: 'user-123',
  firmId: 'firm-abc',
  role: 'FirmAdmin',
  name: 'Admin User',
  email: 'admin@example.com',
};

// Use a fixed year for mock data to avoid hydration issues between server and client rendering
const MOCK_DATA_YEAR = 2023;

const financialYearStart = new Date(MOCK_DATA_YEAR, 3, 1); // April 1, 2023
const financialYearEnd = new Date(MOCK_DATA_YEAR + 1, 2, 31); // March 31, 2024

export const mockCompanies: Company[] = [
  {
    id: 'comp-001',
    companyName: 'Innovate Inc.',
    gstin: '29AABCU9511F1Z5',
    address: '123 Tech Park, Bangalore, KA',
    financialYearStart: financialYearStart,
    financialYearEnd: financialYearEnd,
    firmId: 'firm-abc',
    status: 'Active',
  },
  {
    id: 'comp-002',
    companyName: 'Synergy Solutions',
    gstin: '27AAGCB9812G1Z2',
    address: '456 Business Hub, Mumbai, MH',
    financialYearStart: financialYearStart,
    financialYearEnd: financialYearEnd,
    firmId: 'firm-abc',
    status: 'Archived',
  },
];

export const mockItems: Item[] = [
  { id: 'item-001', name: 'Laptop Pro 15"', type: 'Goods', hsnCode: '84713010', sacCode: undefined, unitPrice: 80000, uqc: 'NOS', gstRate: 18, salesLedgerId: 'led-01', purchaseLedgerId: 'led-purchase-account' },
  { id: 'item-002', name: 'Wireless Mouse', type: 'Goods', hsnCode: '84716060', sacCode: undefined, unitPrice: 1500, uqc: 'NOS', gstRate: 18, salesLedgerId: 'led-01', purchaseLedgerId: 'led-purchase-account' },
  { id: 'item-003', name: 'Accounting Services', type: 'Services', hsnCode: undefined, sacCode: '998222', unitPrice: 20000, uqc: undefined, gstRate: 18, salesLedgerId: 'led-01', purchaseLedgerId: 'led-purchase-account' },
  { id: 'item-004', name: 'IT Support (AMC)', type: 'Services', hsnCode: undefined, sacCode: '998314', unitPrice: 50000, uqc: undefined, gstRate: 18, salesLedgerId: 'led-01', purchaseLedgerId: 'led-purchase-account' },
  { id: 'item-005', name: 'Office Chairs', type: 'Goods', hsnCode: '94013000', sacCode: undefined, unitPrice: 7500, uqc: 'NOS', gstRate: 28, salesLedgerId: 'led-01', purchaseLedgerId: 'led-purchase-account' },
];

export const mockLedgers: Ledger[] = [
  // =================================================================
  // PARENT GROUPS (STANDARD ACCOUNTING HIERARCHY)
  // =================================================================

  // Primary Groups (No Parent)
  {
    id: 'group-assets',
    ledgerName: 'Assets',
    group: 'Assets',
    isGroup: true,
    openingBalance: 0,
    currentBalance: 0,
    balanceType: 'Dr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'group-liabilities',
    ledgerName: 'Liabilities',
    group: 'Liabilities',
    isGroup: true,
    openingBalance: 0,
    currentBalance: 0,
    balanceType: 'Cr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'group-income',
    ledgerName: 'Income',
    group: 'Income',
    isGroup: true,
    openingBalance: 0,
    currentBalance: 0,
    balanceType: 'Cr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'group-expense',
    ledgerName: 'Expenses',
    group: 'Expense',
    isGroup: true,
    openingBalance: 0,
    currentBalance: 0,
    balanceType: 'Dr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },

  // Sub-Groups under Assets
  {
    id: 'group-fixed-assets',
    ledgerName: 'Fixed Assets',
    parentLedgerId: 'group-assets',
    group: 'Assets',
    isGroup: true,
    openingBalance: 0,
    currentBalance: 0,
    balanceType: 'Dr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'group-current-assets',
    ledgerName: 'Current Assets',
    parentLedgerId: 'group-assets',
    group: 'Assets',
    isGroup: true,
    openingBalance: 0,
    currentBalance: 615000,
    balanceType: 'Dr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'group-bank-accounts',
    ledgerName: 'Bank Accounts',
    parentLedgerId: 'group-current-assets',
    group: 'Bank Accounts',
    isGroup: true,
    openingBalance: 0,
    currentBalance: 0,
    balanceType: 'Dr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'group-sundry-debtors',
    ledgerName: 'Sundry Debtors',
    parentLedgerId: 'group-current-assets',
    group: 'Sundry Debtor',
    isGroup: true,
    openingBalance: 0,
    currentBalance: 0,
    balanceType: 'Dr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },

  // Sub-Groups under Liabilities
  {
    id: 'group-capital-account',
    ledgerName: 'Capital Account',
    parentLedgerId: 'group-liabilities',
    group: 'Liabilities',
    isGroup: true,
    openingBalance: 0,
    currentBalance: 0,
    balanceType: 'Cr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'group-current-liabilities',
    ledgerName: 'Current Liabilities',
    parentLedgerId: 'group-liabilities',
    group: 'Liabilities',
    isGroup: true,
    openingBalance: 0,
    currentBalance: 0,
    balanceType: 'Cr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'group-sundry-creditors',
    ledgerName: 'Sundry Creditors',
    parentLedgerId: 'group-current-liabilities',
    group: 'Sundry Creditor',
    isGroup: true,
    openingBalance: 0,
    currentBalance: 0,
    balanceType: 'Cr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'group-duties-taxes',
    ledgerName: 'Duties & Taxes',
    parentLedgerId: 'group-current-liabilities',
    group: 'Liabilities',
    isGroup: true,
    openingBalance: 0,
    currentBalance: 0,
    balanceType: 'Cr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'group-tds-payable',
    ledgerName: 'TDS Payable',
    parentLedgerId: 'group-duties-taxes',
    group: 'Liabilities',
    isGroup: true,
    openingBalance: 0,
    currentBalance: 0,
    balanceType: 'Cr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },

  // Sub-Groups under Income
  {
    id: 'group-sales-accounts',
    ledgerName: 'Sales Accounts',
    parentLedgerId: 'group-income',
    group: 'Income',
    isGroup: true,
    openingBalance: 0,
    currentBalance: 0,
    balanceType: 'Cr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'group-indirect-income',
    ledgerName: 'Indirect Incomes',
    parentLedgerId: 'group-income',
    group: 'Income',
    isGroup: true,
    openingBalance: 0,
    currentBalance: 0,
    balanceType: 'Cr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },

  // Sub-Groups under Expense
  {
    id: 'group-purchase-accounts',
    ledgerName: 'Purchase Accounts',
    parentLedgerId: 'group-expense',
    group: 'Expense',
    isGroup: true,
    openingBalance: 0,
    currentBalance: 0,
    balanceType: 'Dr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'group-indirect-expenses',
    ledgerName: 'Indirect Expenses',
    parentLedgerId: 'group-expense',
    group: 'Expense',
    isGroup: true,
    openingBalance: 0,
    currentBalance: 0,
    balanceType: 'Dr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },

  // =================================================================
  // CHILD LEDGERS (TRANSACTIONAL LEDGERS)
  // =================================================================
  {
    id: 'led-purchase-account',
    ledgerName: 'Purchase Account',
    parentLedgerId: 'group-purchase-accounts',
    group: 'Expense',
    isGroup: false,
    openingBalance: 0,
    currentBalance: 20000,
    balanceType: 'Dr',
    gstApplicable: true,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'led-machinery',
    ledgerName: 'Machinery',
    parentLedgerId: 'group-fixed-assets',
    group: 'Assets',
    isGroup: false,
    openingBalance: 500000,
    currentBalance: 495000,
    balanceType: 'Dr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'led-depreciation',
    ledgerName: 'Depreciation',
    parentLedgerId: 'group-indirect-expenses',
    group: 'Expense',
    isGroup: false,
    openingBalance: 0,
    currentBalance: 5000,
    balanceType: 'Dr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'led-purchase-return',
    ledgerName: 'Purchase Return',
    parentLedgerId: 'group-purchase-accounts',
    group: 'Expense', // It's a contra-expense, so it lives here but will have a Cr balance.
    isGroup: false,
    openingBalance: 0,
    currentBalance: 5000,
    balanceType: 'Cr', // Returns reduce expenses, so it has a credit balance.
    gstApplicable: true,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'led-sales-return',
    ledgerName: 'Sales Return',
    parentLedgerId: 'group-sales-accounts',
    group: 'Income', // It's a contra-income, so it lives here but will have a Dr balance.
    isGroup: false,
    openingBalance: 0,
    currentBalance: 2000,
    balanceType: 'Dr', // Returns reduce income, so it has a debit balance.
    gstApplicable: true,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'led-cash',
    ledgerName: 'Cash in Hand',
    parentLedgerId: 'group-current-assets',
    group: 'Assets',
    isGroup: false,
    openingBalance: 50000,
    currentBalance: 50000,
    balanceType: 'Dr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'led-hdfc',
    ledgerName: 'HDFC Bank',
    parentLedgerId: 'group-bank-accounts',
    group: 'Bank Accounts',
    isGroup: false,
    openingBalance: 500000,
    currentBalance: 480000, // 500k - 25k payment + 5k receipt
    balanceType: 'Dr',
    gstApplicable: false,
    status: 'Active',
    bankDetails: {
      accountHolderName: 'Innovate Inc.',
      accountNumber: '50200012345678',
      ifscCode: 'HDFC0000001',
      bankName: 'HDFC Bank',
      branch: 'Koramangala',
      accountType: 'Current',
    },
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 9, 27),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'led-icici',
    ledgerName: 'ICICI Bank',
    parentLedgerId: 'group-bank-accounts',
    group: 'Bank Accounts',
    isGroup: false,
    openingBalance: 250000,
    currentBalance: 250000,
    balanceType: 'Dr',
    gstApplicable: false,
    status: 'Active',
    bankDetails: {
      accountHolderName: 'Innovate Inc.',
      accountNumber: '000105123456',
      ifscCode: 'ICIC0000001',
      bankName: 'ICICI Bank',
      branch: 'Indiranagar',
      accountType: 'Savings',
    },
    createdAt: new Date(MOCK_DATA_YEAR, 4, 5),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 4, 5),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'led-04',
    ledgerName: 'Client A',
    parentLedgerId: 'group-sundry-debtors',
    group: 'Sundry Debtor',
    isGroup: false,
    openingBalance: 15000,
    currentBalance: 21800, // 15k + 11.8k sale - 5k receipt
    balanceType: 'Dr',
    gstApplicable: true,
    gstDetails: {
      gstRate: 18,
      gstin: '29AABCC1234F1Z5',
      gstClassification: 'Services',
    },
    status: 'Active',
    contactDetails: {
      contactPerson: 'Anil Kumar',
      mobileNumber: '9876543210',
      email: 'anil@clienta.com',
      addressLine1: '789 Client Avenue',
      city: 'Bangalore',
      state: 'Karnataka',
      pan: 'AABCC1234F',
    },
    creditControl: {
      creditLimit: 50000,
      creditPeriod: 30,
    },
    tdsTcsConfig: {
      tcsEnabled: true,
      tcsRate: 1,
    },
    createdAt: new Date(MOCK_DATA_YEAR, 4, 10),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 9, 27),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'led-05',
    ledgerName: 'Supplier B',
    parentLedgerId: 'group-sundry-creditors',
    group: 'Sundry Creditor',
    isGroup: false,
    openingBalance: 25000,
    currentBalance: 47400, // 25k + 22.4k purchase
    balanceType: 'Cr',
    gstApplicable: true,
    gstDetails: {
      gstRate: 12,
      gstClassification: 'Goods',
    },
    tdsTcsConfig: {
      tdsEnabled: true,
      tdsNatureOfPayment: 'contractor',
      tdsDeducteeType: 'other',
      tdsRate: 2,
    },
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 5, 15),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 10, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'led-06',
    ledgerName: 'Share Capital',
    parentLedgerId: 'group-capital-account',
    group: 'Liabilities',
    isGroup: false,
    openingBalance: 1000000,
    currentBalance: 1000000,
    balanceType: 'Cr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'led-01',
    ledgerName: 'Domestic Sales',
    parentLedgerId: 'group-sales-accounts',
    group: 'Income',
    isGroup: false,
    openingBalance: 0,
    currentBalance: 10000,
    balanceType: 'Cr',
    gstApplicable: true,
    gstDetails: {
      gstRate: 18,
      gstClassification: 'Goods',
    },
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 9, 25),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'led-03',
    ledgerName: 'Office Rent',
    parentLedgerId: 'group-indirect-expenses',
    group: 'Expense',
    isGroup: false,
    openingBalance: 0,
    currentBalance: 25000,
    balanceType: 'Dr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 9, 26),
    firmId: 'firm-abc',
    companyId: 'comp-001',
    tdsTcsConfig: {
      tdsEnabled: true,
      tdsNatureOfPayment: 'rent_land',
      tdsSection: '194I',
      tdsRate: 10,
    },
  },
  {
    id: 'led-salaries',
    ledgerName: 'Salaries & Wages',
    parentLedgerId: 'group-indirect-expenses',
    group: 'Expense',
    isGroup: false,
    openingBalance: 0,
    currentBalance: 75000,
    balanceType: 'Dr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 10, 5),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'led-marketing',
    ledgerName: 'Marketing Expenses',
    parentLedgerId: 'group-indirect-expenses',
    group: 'Expense',
    isGroup: false,
    openingBalance: 0,
    currentBalance: 12000,
    balanceType: 'Dr',
    gstApplicable: true,
    gstDetails: { gstRate: 5, gstClassification: 'Services' },
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 10, 10),
    firmId: 'firm-abc',
    companyId: 'comp-001',
    tdsTcsConfig: {
      tdsEnabled: true,
      tdsNatureOfPayment: 'professional',
      tdsSection: '194J',
      tdsRate: 10,
    },
  },
  {
    id: 'led-utilities',
    ledgerName: 'Utilities',
    parentLedgerId: 'group-indirect-expenses',
    group: 'Expense',
    isGroup: false,
    openingBalance: 0,
    currentBalance: 8000,
    balanceType: 'Dr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 10, 12),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'led-cgst',
    ledgerName: 'CGST',
    parentLedgerId: 'group-duties-taxes',
    group: 'Liabilities',
    isGroup: false,
    openingBalance: 0,
    currentBalance: 0,
    balanceType: 'Cr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'led-sgst',
    ledgerName: 'SGST',
    parentLedgerId: 'group-duties-taxes',
    group: 'Liabilities',
    isGroup: false,
    openingBalance: 0,
    currentBalance: 0,
    balanceType: 'Cr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'led-igst',
    ledgerName: 'IGST',
    parentLedgerId: 'group-duties-taxes',
    group: 'Liabilities',
    isGroup: false,
    openingBalance: 0,
    currentBalance: 0,
    balanceType: 'Cr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 3, 1),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 3, 1),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'led-tds-rent',
    ledgerName: 'TDS on Rent (194I)',
    parentLedgerId: 'group-tds-payable',
    group: 'Liabilities',
    isGroup: false,
    openingBalance: 0,
    currentBalance: 2500,
    balanceType: 'Cr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 9, 26),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 9, 26),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
  {
    id: 'led-tds-prof',
    ledgerName: 'TDS on Prof. Fees (194J)',
    parentLedgerId: 'group-tds-payable',
    group: 'Liabilities',
    isGroup: false,
    openingBalance: 0,
    currentBalance: 1200,
    balanceType: 'Cr',
    gstApplicable: false,
    status: 'Active',
    createdAt: new Date(MOCK_DATA_YEAR, 10, 10),
    lastUpdatedAt: new Date(MOCK_DATA_YEAR, 10, 10),
    firmId: 'firm-abc',
    companyId: 'comp-001',
  },
];

export const mockVouchers: Voucher[] = [
  {
    id: 'vch-001',
    voucherNumber: 'SALE-001',
    voucherType: 'Sales',
    date: new Date(MOCK_DATA_YEAR, 9, 25),
    partyLedger: 'led-04', // Client A
    lineItems: [{ ledgerId: 'led-01', amount: 10000, taxRate: 18, taxAmount: 1800 }],
    totalAmount: 11800,
    firmId: 'firm-abc',
    companyId: 'comp-001',
    createdBy: 'user-123',
  },
  {
    id: 'vch-002',
    voucherNumber: 'PAY-001',
    voucherType: 'Payment',
    date: new Date(MOCK_DATA_YEAR, 9, 26),
    partyLedger: 'led-03', // Office Rent
    lineItems: [{ ledgerId: 'led-hdfc', amount: 25000 }], // Paid from HDFC
    totalAmount: 25000,
    firmId: 'firm-abc',
    companyId: 'comp-001',
    createdBy: 'user-123',
  },
  {
    id: 'vch-003',
    voucherNumber: 'RCPT-001',
    voucherType: 'Receipt',
    date: new Date(MOCK_DATA_YEAR, 9, 27),
    partyLedger: 'led-04', // Client A
    lineItems: [{ ledgerId: 'led-hdfc', amount: 5000 }], // Received in HDFC
    totalAmount: 5000,
    firmId: 'firm-abc',
    companyId: 'comp-001',
    createdBy: 'user-123',
  },
  {
    id: 'vch-004',
    voucherNumber: 'PUR-001',
    voucherType: 'Purchase',
    date: new Date(MOCK_DATA_YEAR, 10, 1),
    partyLedger: 'led-05', // Supplier B
    lineItems: [
      {
        ledgerId: 'led-purchase-account',
        amount: 20000,
        taxRate: 12,
        taxAmount: 2400,
      },
    ],
    totalAmount: 22400,
    firmId: 'firm-abc',
    companyId: 'comp-001',
    createdBy: 'user-123',
  },
  {
    id: 'vch-005',
    voucherNumber: 'PAY-002',
    voucherType: 'Payment',
    date: new Date(MOCK_DATA_YEAR, 10, 10),
    partyLedger: 'led-marketing',
    lineItems: [{ ledgerId: 'led-hdfc', amount: 12000 }],
    totalAmount: 12000,
    firmId: 'firm-abc',
    companyId: 'comp-001',
    createdBy: 'user-123',
  },
  {
    id: 'vch-006',
    voucherNumber: 'CN-001',
    voucherType: 'Credit Note',
    date: new Date(MOCK_DATA_YEAR, 10, 15),
    partyLedger: 'led-04', // Client A
    lineItems: [
      { ledgerId: 'led-sales-return', amount: 2000, taxRate: 18, taxAmount: 360 },
    ],
    totalAmount: 2360,
    firmId: 'firm-abc',
    companyId: 'comp-001',
    createdBy: 'user-123',
  },
  {
    id: 'vch-007',
    voucherNumber: 'DN-001',
    voucherType: 'Debit Note',
    date: new Date(MOCK_DATA_YEAR, 10, 18),
    partyLedger: 'led-05', // Supplier B
    lineItems: [
      {
        ledgerId: 'led-purchase-return',
        amount: 5000,
        taxRate: 12,
        taxAmount: 600,
      },
    ],
    totalAmount: 5600,
    firmId: 'firm-abc',
    companyId: 'comp-001',
    createdBy: 'user-123',
  },
  {
    id: 'vch-008',
    voucherNumber: 'JRNL-001',
    voucherType: 'Journal',
    date: new Date(MOCK_DATA_YEAR, 10, 30),
    partyLedger: 'led-depreciation', // Dummy party for journal
    lineItems: [
      { ledgerId: 'led-depreciation', type: 'Dr', amount: 5000 },
      { ledgerId: 'led-machinery', type: 'Cr', amount: 5000 },
    ],
    totalAmount: 5000,
    firmId: 'firm-abc',
    companyId: 'comp-001',
    createdBy: 'user-123',
  },
];

export const mockNotes: Note[] = [
  {
    id: 'note-001',
    title: 'Follow up with Client A',
    description: 'Need to discuss the new project proposal and finalize the terms.',
    priority: 'High',
    status: 'Pending',
    createdAt: new Date(MOCK_DATA_YEAR, 10, 20),
    reminderDate: new Date(), // Today
  },
  {
    id: 'note-002',
    title: 'Q3 GST Filing',
    description: 'Gather all sales and purchase data for GSTR-1 and GSTR-3B filing. Due date is approaching.',
    priority: 'High',
    status: 'Pending',
    createdAt: new Date(MOCK_DATA_YEAR, 11, 1),
    reminderDate: new Date(new Date().setDate(new Date().getDate() + 5)),
  },
  {
    id: 'note-003',
    title: 'Renew Office Insurance',
    description: 'The current policy expires next month. Get quotes from at least 3 providers.',
    priority: 'Medium',
    status: 'Pending',
    createdAt: new Date(MOCK_DATA_YEAR, 10, 15),
  },
  {
    id: 'note-004',
    title: 'Bank Reconciliation - HDFC',
    description: 'Reconciliation for October has been completed and statements are filed.',
    priority: 'Low',
    status: 'Completed',
    createdAt: new Date(MOCK_DATA_YEAR, 10, 5),
  }
];
